### PR TITLE
Compat support: toNumber, toString, string/array ops

### PR DESCRIPTION
**Pull request by towerofnix**
Follow-up to #157, supports leopard-js/sb-edit#90. These too are needed for comprehensive Scratch compatibility. (`toString` technically isn't, but it's cleaner to use consistent casting methods.)

### CODE REVIEW

**Comment by towerofnix** [comment]
@adroitwhiz Changes here should be ready for implementation into #146. They're basically all lifted from scratch-vm.

**Review by adroitwhiz — APPROVED** [review]

**Comment by PullJosh** [comment]
@towerofnix Time for a version bump and new release? If you update the version number with `npm version` and push those changes to Github, we can create a new release on Github and an action will automatically publish to npm.

**Comment by towerofnix** [comment]
Sounds good! I'll give it a version and push. And it's all OK, @adroitwhiz's and my work here all started and ramped up pretty spontaneously so we weren't expecting quick reviews ^_^

**Comment by towerofnix** [comment]
I'm going to give sb-edit a dependencies update locally and then I'll get both of 'em pushed.

**Comment by PullJosh** [comment]
Sweet! sb-edit also has the automatic npm publishing set up, so I think the only thing you need me for is redeploying the website after sb-edit has been published. :)

**Pull request merged**
