### PR TITLE
Replacing consecutive if-statements with a switch-case statement

### PR DESCRIPTION
**Pull request by ThatXliner**
I do not know that much JavaScript. But I do know JavaScript has this. My dad says that I do not need to know the syntax: I just need logic. 

And I do know that switch-case statements are more readable than if statements (maybe faster than if statements?). This seems to be a bit risky. Turn down on my request **if you are cautious. Just don't accept it.**

### CODE REVIEW

**Comment by ThatXliner** [comment]
Maybe put it in a branch first. Then, test if it still works. If it does (woo-hoo!), then it's fine, and I did something productive.

**Comment by callowaysutton** [comment]
You are right that switch statements are faster than ifs, but are slower, in bigger trees than maps.

If you're talking from a readability standpoint I agree that switches are much more easily read but from a performance standpoint, maps would be a lot better. And they seem as if they'd be pragmatically easier to implement but I'm not that well versed in Javascript so that could just be blatantly wrong about that :stuck_out_tongue: 

[Benchmark Used](https://jsben.ch/o0UDx)

**Comment by ThatXliner** [comment]
I haven't profiled the speed yet (I don't know how, and/or I don't have the resources to) so putting it in its own branch would be nice

**Comment by ThatXliner** [comment]
Imma comment to give this a little bit more attention

**Comment by adroitwhiz** [comment]
It looks like this is slightly more code than just using if-statements, and I'm not sure if it would bring much of a speed improvement.

**Pull request closed without merging**
